version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 5000:5000
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # ro = read-only access to the docker.sock
      - ./traefik:/etc/traefik/
      - ./tls:/etc/traefik/tls
    labels:
      traefik.http.routers.api.rule: Host(`traefik.YOURDOMAIN.COM`) # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.service: api@internal # Enable Traefik API.
      traefik.enable: true # Enable Traefik reverse proxy for the Traefik dashboard.

  backend1:
    container_name: backend1
    build:
      context: ./
      dockerfile: Dockerfile
    command: --role backend --server-id 1
    profiles: ["backend"]

  backend2:
    container_name: backend2
    build:
      context: ./
      dockerfile: Dockerfile
    command: --role backend --server-id 2
    profiles: ["backend"]

  backend3:
    container_name: backend3
    build:
      context: ./
      dockerfile: Dockerfile
    command: --role backend --server-id 3
    profiles: ["backend"]

  frontend1:
    container_name: frontend1
    build:
      context: ./
      dockerfile: Dockerfile
    command: --role frontend --server-id 1
    profiles: ["frontend"]

  frontend2:
    container_name: frontend2
    build:
      context: ./
      dockerfile: Dockerfile
    command: --role frontend --server-id 2
    profiles: ["frontend"]
